envfiles/kpi.txt

Per https://github.com/kobotoolbox/kpi/pull/812/

Rename `kobo_playground` to `kobo`

---

envfiles/kpi.txt

Reverts kobotoolbox/kobo-docker#58

Revert "Rename `kobo_playground` to `kobo`"

---

envfiles/kpi.txt

New environment variables from `kobotoolbox/kpi/issues#1062`.

---

README.md
docker-compose.local.yml
docker-compose.server.yml
envfiles/kobocat.txt
envfiles/kpi.txt

Also requires merging kobotoolbox/kpi/pull/1097 and kobotoolbox/kobocat/pull/316.

Facilitate remote Python debugging with PyDev.

---

nginx/nginx_site_https.conf.tmpl
nginx/proxy_pass.conf.tmpl
nginx/uwsgi_pass.conf.tmpl

Part of kobotoolbox/tasks#114.
Needed for kobotoolbox/kpi#1128.

Strip and pass `X-Forwarded-For` for kobotoolbox/tasks#114

---

.gitignore
nginx/nginx_site_https.conf.tmpl
nginx/uwsgi_pass.conf.tmpl

Fixes #147. @noliveleger, could you make sure this looks okay to you and, if so, mirror this change for OCHA configurations?

Increase uWSGI buffer size to fix #147

---

docker-compose.frontend.yml

OCHA version of https://github.com/kobotoolbox/kobo-docker/pull/152

Use Enketo Express 1.55.6 release w/ extra widgets

---

docker-compose.local.yml
docker-compose.server.yml
envfiles/aws.txt

Volume mapping and S3 template for KPI media

---

envfiles/kobocat.txt

Affects *NEW USERS* only! Read notes at
https://github.com/kobotoolbox/kobocat/pull/403
Closes #155

Add configuration for kobotoolbox/kobocat#335

---

docker-compose.local.yml
docker-compose.server.yml

Pin KC, KPI, and EE tags

---

enketo_express/config.json

Enable literacy widget in Enketo Express

---

envfiles/kobocat.txt
envfiles/kpi.txt

Add environment variables for Celery task timeouts

---

README.md

Just the same as #222, but newly created to show the correct diff after #215.

Final merge of `kobo-install` into `master`

---

nginx/nginx_site_default.conf.tmpl

Fixed prefixed dkobo urls redirection

---

docker-compose.frontend.yml

As suggested by @jnm. 
Map volume to a more implicit folder 
Related to #235

Mapped enketo checksum folder to subdirectory of enketo folder

---

docker-compose.backend.master.yml
docker-compose.backend.template.yml

and removed (redis) duplicates from master composer file.
Fixes #240

Added missing volumes for backups in master template

---

README.md

Just trying to get a github shirt while making small contributions ☺️

Fix Lucidchart link in README

---

postgres/master/clone_data_from_kc_to_kpi.sh

…and use `pg_dump` instead of CSV copy in order to clone the schema as well as
the data

Create KPI database when cloning from KoBoCAT

---

postgres/master/clone_data_from_kc_to_kpi.sh

Related to https://github.com/kobotoolbox/kpi/issues/2543

Make the database cloning script more robust

---

deployments/envfiles/kpi.txt
docker-compose.frontend.yml

Merge after https://github.com/kobotoolbox/kpi/pull/2575

Remove references to Whoosh

---

deployments/enketo_express/config.json

https://github.com/kobotoolbox/tasks/issues/352#issuecomment-606720763

Standardize Enketo config; revert order of widgets

---

docker-compose.frontend.yml

Use persistent storage for KPI FileFields

---

docker-compose.frontend.override.yml.sample
docker-compose.frontend.yml
uwsgi/kc_uwsgi.ini
uwsgi/kpi_uwsgi.ini

Customize uWSGI timeouts for harakiri and worker reloads using environment variables

---

docker-compose.frontend.override.yml.sample
docker-compose.frontend.yml
nginx/docker-entrypoint.d/30-init-kobo-nginx.sh
nginx/kobo-docker-scripts/templates/uwsgi_pass.conf.tmpl

Related to https://github.com/kobotoolbox/kobo-install/pull/97/files

Set NGINX uwsgi pass timeout from environment variable

---

redis/entrypoint.sh

Related to https://github.com/kobotoolbox/kobo-install/pull/98/files

Support empty REDIS password

---

doc/source/development.rst
docker-compose.frontend.yml
nginx/docker-entrypoint.d/30-init-kobo-nginx.sh
uwsgi/kc_uwsgi.ini

Fixes #301, after these steps are followed:

Connect to KoBoCAT container on port 8001

---

docker-compose.backend.template.yml
docker-compose.frontend.yml

Restart containers `always` instead of `on-failure`

---

postgres/shared/init_02_set_postgres_config.sh
postgres/toggle-backup-activation.sh

Added installation of Wal-e Postgres backup when starting the Postgres docker. 
Configuration of the ENVDIR, as well as the crontab for a full backup every Sunday at 20:00 UTC.

Install wal-e, envdir and crontab

---

nginx/docker-entrypoint.d/30-init-kobo-nginx.sh
nginx/kobo-docker-scripts/nginx.conf
nginx/kobo-docker-scripts/templates/nginx_site_default.conf.tmpl

1. [x] If you've added code that should be tested, add tests
-No code written but moved and cleaned up nginx config files.
2. [n/a] If you've changed APIs, update (or create) the documentation
3. [x] Ensure the tests pass
4. [x] Make sure that your code lints and that you've followed [our coding style]
5. [x] Write a description of your work suitable for publishing on [our forum]
6. [x] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)
Gzip is now enabled on the server for all API responses.
This means a decrease in the time it takes to request data and have the response returned to the user.
Removed parameters that are no longer used for production or development.
Closes kobotoolbox/kpi#2917

Kpi#2917 django api compression

---

README.md
doc/March-2019-Upgrade.md
doc/May-2022-Upgrade.md
docker-compose.backend.template.yml
docker-compose.frontend.override.yml.sample
nginx/maintenance/index.html.tmpl
postgres/entrypoint.sh
postgres/primary/clone_data_from_kc_to_kpi.sh
postgres/primary/drop_kpi_tables_in_kc.sh
postgres/shared/postgres.conf
redis/entrypoint.sh

kobotoolbox/kpi#3740
closes #270

Upgrade PostgreSQL to v14.2, MongoDB to v5 and Redis to v6.2 

---

docker-compose.frontend.yml

Removed the overrides for the Enketo Express icons

remove Enketo Express overrides for icons

---

.gitignore
README.md
doc/November-2022-Upgrade.md

Stretch and PostgreSQL 9.5 are not supported anymore by Debian. It adds extra steps to use archive packages instead.

Update PostgreSQL upgrade documentation

---

doc/November-2022-Upgrade.md

Update documentation to fix `apt update` error when trying to use PostgreSQL archive repository

Rearrange the order of commands to run to be able to add apt archive packages
