kobotoolbox/kobo-docker

- base_images/base-kobos/Dockerfile
New Python packages need to be installed for the `requests` library to support the SNI configuration used on staging server `mp03`. This development package is a prerequisite of https://github.com/kobotoolbox/dkobo/pull/636.
> Include `libffi-dev`, required for SNI support

- scripts/create_kobo_superuser.bash
Using shell expansion to get string values into python code was
running into issues with escaping. Since the shell script used
environmental variables, just read those from within Python.
> Fix #81, read user/pass from env var not str exp.

- docker-compose.local.yml
- docker-compose.server.yml
- nginx/nginx_site_https.conf.tmpl
- nginx/proxy_pass.conf.tmpl
- nginx/uwsgi_pass.conf.tmpl
After #115.
kobotoolbox/kobocat#366 required first.
> Mount KPI and KC logs to the host filesystem

- nginx/proxy_pass.conf.tmpl
when `proxy_pass`ing to `runserver_plus` since [Django expects that](https://github.com/django/django/blob/1.8.18/django/http/request.py#L79).
Fixes #119.
> Include `$proxy_port` in the Host header

- docker-compose.frontend.server.yml
- uwsgi/kc_uwsgi.ini
- uwsgi/kpi_uwsgi.ini
* Spawn up to 24 workers for each app (as long as RSS stays below 7G)
* Reload individual workers if their RSS exceeds 512M
* Set `cheaper-overload = 1` to add workers right away if all existing are busy
* Enable `harakiri` and threading on KPI to match KC
> OCHA uWSGI-related changes

- README.md
As kobo wont run out of the box anymore without setting proper permissions to media folders I suggest adding this information to the INITIAL setup part of the README.MD until it has been resolved, as many people will have to go through the issues list to address this.
> Update README.MD for initial setup (Bugfix)

- nginx/nginx_site_http.conf.tmpl
Closes kobotoolbox/tasks#262 (`413 Request Entity Too Large` error)
> Raise upload limit for all apps to 100M

- docker-compose.frontend.yml
Allow to keep checksum version even if the container is removed
To be efficient, `encryption key` should be filled up in `enketo_express` env file.
```
{
"app name": "Enketo Express for KoBo Toolbox",
"linked form and data server": {
"name": "KoBo Toolbox",
"server url": "",
"encryption key": "xxxxxxxxxxxxxxxxxxxx"
},
...
}
```
Otherwise a new key is regenerate each time and checks differ. 
Related to https://github.com/enketo/enketo-express/pull/91
> Added new volume to enketo-express to persist files on disk

- postgres/master/postgres.conf
- postgres/slave/postgres.conf
- postgres/toggle-backup-activation.sh
According to https://www.pgconfig.org/#/tuning, 
Default settings postgres have been lower to fit 2GB of RAM. 
`smart-open` pip dependency has been frozen to ver: `1.7.1`. Newer version fails to build and backup to S3 can't run.
> Postgres lower default values

- nginx/nginx_site_default.conf.tmpl
Fixes #234
Requires https://github.com/kobotoolbox/kobocat/pull/548
> Accept a double-encoded S3 URL from KoBoCAT

- nginx/logs_with_host.conf
Depends on kobotoolbox/kpi#2300, kobotoolbox/kobocat#559
Closes #245 
**Weakness**: this doesn't affect logging at the load-balancer level, so it will remain difficult to match up  requests that go through a temporary instance with their corresponding users.
> Include username in NGINX log for every request

- nginx/nginx_command.bash
- nginx/proxy_pass.conf.tmpl
When dev mode is enabled: DJANGO reads `X_FORWARDED_HOST` to return correct `$host`. 
But when `kpi` is corresponding with `kc` internally, the $host is wrong (i.e. returns domain name on internal network) with custom port if exists.
The hyperlinks in serializers in `kc` are build on top of this value and sent to `kpi`. `kpi` uses those value for subsequents calls but fails.
> Force X_FORWARDED_HOST when dev mode is enabled

- base_images/base-kobos/Dockerfile
- scripts/wait_for_kpi.bash
- `dockerize`: updated to version 0.6.1
- `pip`: don't force install of version 8 (as versions are controlled in `kobocat` and `kpi` build).
Closes #94
> Update dockerize and pip

- docker-compose.backend.template.yml
- mongo/entrypoint.sh
- postgres/entrypoint.sh
- redis/entrypoint.sh
…when stopping Docker containers. Fixes #276.
<pre><font color="#C4A000">kobo-docker_redis_main_1 exited with code 137</font>
<font color="#75507B">kobo-docker_redis_cache_1 exited with code 137</font>
<font color="#06989A">kobo-docker_mongo_1 exited with code 137</font>
<font color="#4E9A06">kobo-docker_postgres_1 exited with code 137</font>
</pre>
<pre><font color="#C4A000">kobo-docker_redis_main_1 exited with code 0</font>
<font color="#4E9A06">kobo-docker_redis_cache_1 exited with code 0</font>
<font color="#06989A">kobo-docker_mongo_1 exited with code 0</font>
<font color="#75507B">kobo-docker_postgres_1 exited with code 0</font>
</pre>
> Pass signals and give grace period to database servers

- docker-compose.backend.template.yml
- postgres/master/drop_kpi_tables_in_kc.sh
I have also changed the Postgres image to `PostGIS` image. 
I had a weird issue with the PostGIS version when pulling a fresh mdillon/postgis image. (tbh, It happened once and could not reproduce it again)
Not included in kobo-install yet but it will be useful for our production servers to save some space.
> Clean-up KoBoCAT database after two databases upgrade

- uwsgi/kc_uwsgi.ini
- uwsgi/kpi_uwsgi.ini
I forgot to wrap environment variables in `$(..)` 
```
harakiri            = KPI_UWSGI_HARAKIRI
worker-reload-mercy = KPI_UWSGI_WORKER_RELOAD_MERCY
```
and 
```
harakiri            = KC_UWSGI_HARAKIRI
worker-reload-mercy = KC_UWSGI_WORKER_RELOAD_MERCY
```
In my tests (`KPI_UWSGI_HARAKIRI = 15`and  `import time; time.sleep(20)`), I thought it was working as excepted because of the logs. I was wrong, Haraki was not called here.
```
Tue Jun  9 21:11:04 2020 - worker 2 (pid: 144) is taking too much time to die...NO MERCY !!!
Tue Jun  9 21:11:05 2020 - worker 2 (pid: 144) is taking too much time to die...NO MERCY !!!
```
With correctly wrapped variables $(...),I get correct behaviour.
```
Tue Jun  9 21:15:17 2020 - *** HARAKIRI ON WORKER 1 (pid: 163, try: 1) ***
Tue Jun  9 21:15:17 2020 - …
```
> PR #289 fix

- env/envfile.txt
since it's still used by KPI and KoBoCAT
> Restore `ENKETO_API_TOKEN` for now

- mongo/toggle-backup-activation.sh
- postgres/backup-to-disk.bash
- postgres/backup-to-s3.py
- postgres/toggle-backup-activation.sh
- redis/toggle-backup-activation.sh
The backups take more time to complete and overlap on busy hours.
The application becomes unresponsive
> Lower backup priorities and make PostgreSQL backups run in parallel.

- postgres/toggle-backup-activation.sh
Error sending WAL Postgres files to S3 :
```
wal_e.main   ERROR    MSG: bad S3, Windows Azure Blob Storage, OpenStack Swift, Google Cloud Storage or File URL scheme passed
DETAIL: The scheme  was passed when "s3", "wabs", "swift", "gs", or "file" was expected.
STRUCTURED: time=2020-11-06T09:40:43.933816-00 pid=1202
[2020-11-06 09:40:43 UTC] LOG:  archive command failed with exit code 1
[2020-11-06 09:40:43 UTC] DETAIL:  The failed archive command was: envdir /var/lib/postgresql/data/wal-e.d/env wal-e wal-push pg_xlog/000000010000000000000001
[2020-11-06 09:40:43 UTC] WARNING:  archiving transaction log file "000000010000000000000001" failed too many times, will try again later
```
The WALE_S3_PREFIX variable must be : ```s3://[BUCKET_NAME]/postgres/``` instead of just ```[BUCKET_NAME]```.
> Modification of the WALE_S3_PREFIX variable

- docker-compose.frontend.yml
- nginx/kobo-docker-scripts/templates/nginx_site_default.conf.tmpl
Allow customization of login background and logos when using local (non-S3) storage, by serving those images in a publicly-accessible location
Fixes #175
Related to kobotoolbox/kpi#1738
> Serve public KPI media via NGINX

- mongo/entrypoint.sh
- mongo/init_01_add_index.sh
- mongo/post_startup.sh
MongoDB can be really slow when sorting or counting documents when the database contains lots of records and the query contains more than one index (e.g. `_userform_id` and `_id`). 
It happens because MongoDB does not know what index to choose and make sequential scans to read all the data - which is really slow on big database. 
Using a compound index of each field used in such queries make MongoDB return the data way faster. 
This new index is created when the DB is initialized. 
For retro-compatibility with existing installations, it is also created in background when MongoDB starts. MongoDB does not complain to create an index which already exists **if and only if** it's created with the same options.
> Add compound index for fields `_userform_id` and `_id` to MongoDB

- mongo/entrypoint.sh
Necessary because `/entrypoint.sh` is a symlink to `/usr/local/bin/docker-entrypoint.sh` in the Dockerfile for 3.4, but it's removed altogether in 3.6:
https://github.com/docker-library/mongo/blob/7eb154bcb0b90a70effe73dd8ab77783ce85434a/3.4/Dockerfile#L103
https://github.com/docker-library/mongo/blob/38648d9dddd6a6f87f0d47885bf6525c20b63557/3.6/Dockerfile#L107-L108
This does not break anything for 3.4 in my testing.
See also kobotoolbox/tasks#420
> Update MongoDB entrypoint path

- docker-compose.frontend.yml
- uwsgi/kpi_uwsgi.ini
KPI uWSGI configuration (`uwsgi.ini`) was running as user with priviliges unlike KoBoCAT configuration.
This requires changes in the KPI Docker, so that the user is set within the build.
> Run KPI uWSGI workers as a non-root user

- .gitignore
kobo-install creates a file which contains random unique string for internal purpose. 
To avoid adding to this repo, let's add it to .gitignore.
> Add ".uniqid" to .gitignore

- nginx/kobo-docker-scripts/templates/uwsgi_pass.conf.tmpl
Avoid NGINX to send KoBoCAT traffic to KPI container and vice versa
Force NGINX to resolve `kpi` and `kobocat` domain names on the docker network on every proxied request.
Closes #332
> Fix NGINX DNS cache resolution issue

- scripts/wait_for_postgres.bash
This gets rid of scary-looking PostgreSQL log entries like:
LOG:  incomplete startup packet
FATAL:  password authentication failed for user "root"
DETAIL:  Role "root" does not exist.
Connection matched pg_hba.conf line 15: "host    all all all md5"
> Set username and password when calling `pg_isready`

- nginx/kobo-docker-scripts/nginx.conf
Removes the nginx version from the `server` response header by setting server_tokens off in nginx.conf.
Tested normal and maintenance mode using kobo-install.
> Remove nginx version from response header

- nginx/kobo-docker-scripts/templates/proxy_pass.conf.tmpl
Let the HTTPS reverse proxy send the correct value
Only affect dev environment when using NGINX with Django webserver. 
It's useful for Django to set the correct value based on `SECURE_PROXY_SSL_HEADER` env variable.
> Fix wrong scheme with HTTPS when using Django development web server

- docker-compose.frontend.yml
Fixed an issue with the incorrect path in the Celery Beat entrypoint.
The Celery Beat entrypoint was misconfigured due to an incorrect path, preventing scheduled tasks from initializing correctly.
> fix(celery): correct Celery Beat entrypoint path

- mongo/init_01_add_index.sh
add double-quotes to index name "formhub/uuid" to prevent syntax error during startup of mongo container
this error makes the mongo default entry-point script /usr/local/bin/docker-entrypoint.sh aborts pre-maturely
which results in not executing the second init script init_02_create_user.sh which creates kobo user
> Fix syntax for index creation in init_01_add_index.sh

- mongo/init_01_add_index.sh
The typical query gets latest submissions first, so descending order on the submission time is correct
> Correct discrepancy in MongoDB index

- nginx/kobo-docker-scripts/templates/nginx_site_default.conf.tmpl
Redirect root of KoboCAT domain name to KPI domain name. Other URLs, not whitelisted, still return a 404.
It matches k8s production NGINX settings
> fix: redirect root of KoboCAT domain name to KPI domain name
